# Generated by Django 3.0.4 on 2020-03-07 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.TimeField()),
                ('on_sale', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveSmallIntegerField()),
                ('purchased_seats', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.screen'),
        ),
    ]
