# Generated by Django 3.0.4 on 2020-03-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='purchased_seats',
        ),
        migrations.AddField(
            model_name='movie',
            name='purchased_seats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
