# Generated by Django 3.0.4 on 2020-03-08 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200308_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Screen'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='showtime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Movie'),
        ),
    ]
